services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PORT=8000
      - MY_PROJECT_NAME=Hello World Project
      - API_KEY=abc123
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    env_file:
      - .env
    volumes:
      - "./backend/src:/app"
    depends_on:
      - db_service
    develop:
      watch:
        - action: rebuild
          path: "./backend/Dockerfile"
        - action: rebuild
          path: "./backend/requirements.txt"
        - action: restart
          path: "./backend/src/"

  db_service:
    image: postgres:17.5
    ports:
      - "5432:5432"
    volumes:
      - managed_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=mydb

  # static_html:
  #   build:
  #     context: ./static_html
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   command: python -m http.server 8000
  #   volumes:
  #     - "./static_html/src:/app"

volumes:
  managed_db_data:
